<?php
declare(strict_types=1);

/*
 * CreatorPulse v2 Audio Room feature language catalog.
 * Feature strings load after the base language file and before database overrides.
 */
$eng = [
    'admin_menu_audio_rooms' => 'Audio Rooms',
    'admin_menu_audio_room_earnings' => 'Audio Room earnings',
    'admin_menu_settings_audio_rooms' => 'Audio Room settings',
    'admin_audio_rooms_title' => 'Audio Rooms',
    'admin_audio_rooms_intro' => 'Monitor live rooms, attendance, access and room earnings.',
    'admin_audio_rooms_summary' => 'Audio Room summary',
    'admin_audio_rooms_total' => 'Total rooms',
    'admin_audio_rooms_live' => 'Live now',
    'admin_audio_rooms_ended' => 'Ended rooms',
    'admin_audio_rooms_gross' => 'Gross revenue',
    'admin_audio_rooms_platform' => 'Platform revenue',
    'admin_audio_rooms_platform_revenue' => 'Platform revenue',
    'admin_audio_rooms_tickets' => 'tickets',
    'admin_audio_rooms_tips' => 'tips',
    'admin_audio_rooms_manage' => 'Manage rooms',
    'admin_audio_rooms_open' => 'Open Audio Rooms',
    'admin_audio_rooms_open_access' => 'Open access',
    'admin_audio_rooms_open_public' => 'Open public room list',
    'admin_audio_rooms_earnings' => 'Earnings',
    'admin_audio_rooms_search_placeholder' => 'Room title, host or room ID',
    'admin_audio_rooms_access' => 'Access',
    'admin_audio_rooms_attendance' => 'Attendance',
    'admin_audio_rooms_room' => 'Room',
    'admin_audio_rooms_speakers' => 'speakers',
    'admin_audio_rooms_online' => 'online',
    'admin_audio_rooms_view' => 'View room',
    'admin_audio_rooms_end' => 'End room',
    'admin_audio_rooms_cancel' => 'Cancel room',
    'admin_audio_rooms_empty' => 'No Audio Rooms match these filters.',
    'admin_audio_room_access_all' => 'All access types',
    'admin_audio_room_access_free' => 'Free',
    'admin_audio_room_access_paid' => 'Paid',
    'admin_audio_room_status_all' => 'All statuses',
    'admin_audio_room_status_created' => 'Created',
    'admin_audio_room_status_live' => 'Live',
    'admin_audio_room_status_ended' => 'Ended',
    'admin_audio_room_status_cancelled' => 'Cancelled',
    'admin_audio_room_settings_title' => 'Audio Room Settings',
    'admin_audio_room_settings_intro' => 'Control room availability, paid access, capacity and community defaults from one place.',
    'admin_audio_room_overview' => 'Audio Room overview',
    'admin_audio_room_features' => 'Features and access',
    'admin_audio_room_features_hint' => 'Choose which room capabilities are available to creators and listeners.',
    'admin_audio_rooms_enabled' => 'Enable audio rooms',
    'admin_audio_rooms_enabled_hint' => 'Shows Audio Rooms entry points and allows users to join eligible rooms.',
    'admin_audio_room_chat_enabled' => 'Enable room chat',
    'admin_audio_room_chat_hint' => 'Allows participants to exchange text messages inside rooms.',
    'admin_audio_room_paid_enabled' => 'Allow paid creator rooms',
    'admin_audio_room_paid_hint' => 'Approved creators may charge an entry price.',
    'admin_audio_room_custom_price' => 'Allow custom creator prices',
    'admin_audio_room_custom_price_hint' => 'When disabled, creators must choose an approved preset.',
    'admin_audio_room_pricing' => 'Pricing rules',
    'admin_audio_room_pricing_hint' => 'Amounts use the site currency and the global payment fee and tax configuration.',
    'admin_audio_room_price_presets' => 'Price presets',
    'admin_audio_room_price_presets_hint' => 'Comma-separated positive amounts.',
    'admin_audio_room_min_price' => 'Minimum paid entry',
    'admin_audio_room_max_price' => 'Maximum paid entry',
    'admin_audio_room_limits' => 'Duration and capacity',
    'admin_audio_room_limits_hint' => 'Protect room quality by setting daily usage and attendance limits.',
    'admin_audio_room_daily_limit' => 'Non-creator daily minutes',
    'admin_audio_room_zero_unlimited' => '0 means unlimited.',
    'admin_audio_room_max_speakers' => 'Maximum speakers',
    'admin_audio_room_max_listeners' => 'Maximum listeners',
    'admin_audio_room_title_prefix' => 'Default title prefix',
    'admin_audio_room_title_prefix_placeholder' => 'Example: Room with',
    'admin_audio_room_agora_readiness' => 'Agora readiness',
    'admin_audio_room_agora_hint' => 'Audio Rooms reuse the protected Agora credentials configured in Live Settings.',
    'admin_audio_room_agora_ready' => 'Ready',
    'admin_audio_room_agora_missing' => 'Configuration required',
    'admin_audio_room_manage_agora' => 'Manage Agora credentials',
    'admin_audio_room_earnings_title' => 'Audio Room earnings',
    'admin_audio_room_earnings_subtitle' => 'Review room tickets, tips, creator net earnings and platform revenue.',
    'admin_audio_room_earnings_summary' => 'Earnings summary',
    'admin_audio_room_earnings_gross' => 'Gross volume',
    'admin_audio_room_earnings_creator_net' => 'Creator net',
    'admin_audio_room_earnings_creator_net_help' => 'Credited to room creators',
    'admin_audio_room_earnings_platform' => 'Platform revenue',
    'admin_audio_room_earnings_platform_help' => 'Fees and tax allocation',
    'admin_audio_room_earnings_tickets' => 'tickets',
    'admin_audio_room_earnings_tips' => 'tips',
    'admin_audio_room_earnings_successful' => 'successful',
    'admin_audio_room_earnings_transactions' => 'Transactions',
    'admin_audio_room_earnings_manage_rooms' => 'Manage rooms',
    'admin_audio_room_earnings_settings' => 'Room settings',
    'admin_audio_room_earnings_export' => 'Export CSV',
    'admin_audio_room_earnings_search' => 'Search',
    'admin_audio_room_earnings_search_placeholder' => 'Room, user, reference or ID',
    'admin_audio_room_earnings_type' => 'Type',
    'admin_audio_room_earnings_type_all' => 'All transaction types',
    'admin_audio_room_earnings_type_ticket' => 'Room tickets',
    'admin_audio_room_earnings_type_tip' => 'Room tips',
    'admin_audio_room_earnings_type_ticket_single' => 'Ticket',
    'admin_audio_room_earnings_type_tip_single' => 'Tip',
    'admin_audio_room_earnings_status' => 'Status',
    'admin_audio_room_earnings_status_all' => 'All statuses',
    'admin_audio_room_earnings_status_paid' => 'Paid',
    'admin_audio_room_earnings_status_completed' => 'Completed',
    'admin_audio_room_earnings_status_succeeded' => 'Succeeded',
    'admin_audio_room_earnings_status_pending' => 'Pending',
    'admin_audio_room_earnings_status_failed' => 'Failed',
    'admin_audio_room_earnings_status_cancelled' => 'Cancelled',
    'admin_audio_room_earnings_status_canceled' => 'Canceled',
    'admin_audio_room_earnings_status_refunded' => 'Refunded',
    'admin_audio_room_earnings_from' => 'From',
    'admin_audio_room_earnings_to' => 'To',
    'admin_audio_room_earnings_per_page' => 'Per page',
    'admin_audio_room_earnings_apply' => 'Apply',
    'admin_audio_room_earnings_clear' => 'Clear',
    'admin_audio_room_earnings_results' => 'results',
    'admin_audio_room_earnings_empty' => 'No Audio Room transactions match these filters.',
    'admin_audio_room_earnings_col_date' => 'Date',
    'admin_audio_room_earnings_col_type' => 'Type',
    'admin_audio_room_earnings_col_reference' => 'Reference',
    'admin_audio_room_earnings_col_room' => 'Room',
    'admin_audio_room_earnings_col_buyer' => 'Buyer',
    'admin_audio_room_earnings_col_creator' => 'Creator',
    'admin_audio_room_earnings_col_gross' => 'Gross',
    'admin_audio_room_earnings_col_net' => 'Creator net',
    'admin_audio_room_earnings_col_platform' => 'Platform',
    'admin_audio_room_earnings_col_status' => 'Status',
    'admin_audio_room_earnings_col_invoice' => 'Invoice',
    'admin_audio_room_earnings_view_invoice' => 'View',
    'admin_audio_room_earnings_pagination' => 'Transaction pages',
    'admin_audio_room_invoice_label' => 'Invoice',
    'admin_audio_room_invoice_ticket' => 'Audio Room ticket',
    'admin_audio_room_invoice_tip' => 'Audio Room tip',
    'admin_audio_room_invoice_back' => 'Back to earnings',
    'admin_audio_room_invoice_pdf' => 'Download PDF',
    'admin_audio_room_invoice_not_found' => 'Audio Room invoice not found',
    'admin_audio_room_invoice_not_found_help' => 'The transaction may be incomplete or its invoice has not been issued.',
    'admin_audio_room_invoice_billed_to' => 'Billed to',
    'admin_audio_room_invoice_creator' => 'Creator',
    'admin_audio_room_invoice_date' => 'Issued',
    'admin_audio_room_invoice_reference' => 'Reference',
    'admin_audio_room_invoice_provider' => 'Provider',
    'admin_audio_room_invoice_status' => 'Status',
    'admin_audio_room_invoice_finance' => 'Audio Room finance',
    'admin_audio_room_invoice_gross' => 'Gross amount',
    'admin_audio_room_invoice_fee' => 'Platform fee',
    'admin_audio_room_invoice_tax' => 'Tax allocation',
    'admin_audio_room_invoice_net' => 'Creator net',
    'admin_dashboard_audio_room_gross' => 'Audio Room gross',
    'admin_dashboard_audio_room_creator_net' => 'Audio Room creator net',
    'admin_dashboard_audio_room_platform_fee' => 'Audio Room platform revenue',
    'admin_dashboard_audio_room_tickets' => 'Room ticket revenue',
    'admin_dashboard_audio_room_tips' => 'Room tip revenue',
    'admin_dashboard_legend_audio_room_tickets' => 'Audio Room tickets',
    'admin_dashboard_legend_audio_room_tips' => 'Audio Room tips',
    'settings_dashboard_audio_room_ticket' => 'Room ticket',
    'settings_dashboard_audio_room_tip' => 'Room tip',
    'settings_dashboard_breakdown_audio_room_tickets' => 'Audio Room tickets',
    'settings_dashboard_breakdown_audio_room_tickets_short' => 'Room tickets',
    'settings_dashboard_breakdown_audio_room_tips' => 'Audio Room tips',
    'settings_dashboard_breakdown_audio_room_tips_short' => 'Room tips',
    'settings_dashboard_empty_audio_room_earnings' => 'No Audio Room earnings recorded yet.',
    'settings_dashboard_recent_audio_room_earnings' => 'Recent Audio Room earnings',
    'audio_room_ticket_payment_title' => 'Audio Room ticket',
    'audio_room_tip_payment_title' => 'Audio Room tip',
    'audio_room_audience_restricted' => 'You cannot access this Audio Room.',
    'audio_room_ended' => 'This Audio Room has ended.',
    'audio_room_label' => 'Audio Room',
    'audio_room_not_found' => 'Audio Room not found.',
    'audio_room_untitled' => 'Untitled Audio Room',
    'invalid_audio_room_price' => 'Enter a valid Audio Room price.',
    'settings_payments_type_audio_room_ticket' => 'Audio Room ticket',
    'settings_payments_type_audio_room_tip' => 'Audio Room tip',
    'invoice_line_audio_room_ticket_description' => 'Audio Room ticket: %s',
    'invoice_line_audio_room_tip_description' => 'Audio Room tip: %s',
];

$tr = array_replace($eng, [
    'admin_menu_audio_rooms' => 'Sesli Odalar',
    'admin_menu_audio_room_earnings' => 'Sesli Oda kazançları',
    'admin_menu_settings_audio_rooms' => 'Sesli Oda ayarları',
    'admin_audio_rooms_title' => 'Sesli Odalar',
    'admin_audio_rooms_intro' => 'Canlı odaları, katılımı, erişimi ve oda kazançlarını yönetin.',
    'admin_audio_rooms_summary' => 'Sesli Oda özeti',
    'admin_audio_rooms_total' => 'Toplam oda',
    'admin_audio_rooms_live' => 'Şu anda canlı',
    'admin_audio_rooms_ended' => 'Sona eren odalar',
    'admin_audio_rooms_gross' => 'Brüt gelir',
    'admin_audio_rooms_platform' => 'Platform geliri',
    'admin_audio_rooms_platform_revenue' => 'Platform geliri',
    'admin_audio_rooms_tickets' => 'bilet',
    'admin_audio_rooms_tips' => 'bahşiş',
    'admin_audio_rooms_manage' => 'Odaları yönet',
    'admin_audio_rooms_open' => 'Sesli Odaları aç',
    'admin_audio_rooms_open_access' => 'Açık erişim',
    'admin_audio_rooms_open_public' => 'Herkese açık oda listesini aç',
    'admin_audio_rooms_earnings' => 'Kazançlar',
    'admin_audio_rooms_search_placeholder' => 'Oda başlığı, yönetici veya oda kimliği',
    'admin_audio_rooms_access' => 'Erişim',
    'admin_audio_rooms_attendance' => 'Katılım',
    'admin_audio_rooms_room' => 'Oda',
    'admin_audio_rooms_speakers' => 'konuşmacı',
    'admin_audio_rooms_online' => 'çevrimiçi',
    'admin_audio_rooms_view' => 'Odayı görüntüle',
    'admin_audio_rooms_end' => 'Odayı bitir',
    'admin_audio_rooms_cancel' => 'Odayı iptal et',
    'admin_audio_rooms_empty' => 'Bu filtrelerle eşleşen Sesli Oda yok.',
    'admin_audio_room_access_all' => 'Tüm erişim türleri',
    'admin_audio_room_access_free' => 'Ücretsiz',
    'admin_audio_room_access_paid' => 'Ücretli',
    'admin_audio_room_status_all' => 'Tüm durumlar',
    'admin_audio_room_status_created' => 'Oluşturuldu',
    'admin_audio_room_status_live' => 'Canlı',
    'admin_audio_room_status_ended' => 'Sona erdi',
    'admin_audio_room_status_cancelled' => 'İptal edildi',
    'admin_audio_room_settings_title' => 'Sesli Oda Ayarları',
    'admin_audio_room_settings_intro' => 'Oda kullanılabilirliğini, ücretli erişimi, kapasiteyi ve topluluk varsayılanlarını tek yerden yönetin.',
    'admin_audio_room_overview' => 'Sesli Oda genel görünümü',
    'admin_audio_room_features' => 'Özellikler ve erişim',
    'admin_audio_room_features_hint' => 'İçerik üreticileri ve dinleyiciler için kullanılabilir oda özelliklerini seçin.',
    'admin_audio_rooms_enabled' => 'Sesli odaları etkinleştir',
    'admin_audio_rooms_enabled_hint' => 'Sesli Oda girişlerini gösterir ve uygun kullanıcıların odalara katılmasını sağlar.',
    'admin_audio_room_chat_enabled' => 'Oda sohbetini etkinleştir',
    'admin_audio_room_chat_hint' => 'Katılımcıların oda içinde metin mesajı göndermesine izin verir.',
    'admin_audio_room_paid_enabled' => 'Ücretli içerik üreticisi odalarına izin ver',
    'admin_audio_room_paid_hint' => 'Onaylı içerik üreticileri giriş ücreti belirleyebilir.',
    'admin_audio_room_custom_price' => 'Özel içerik üreticisi fiyatlarına izin ver',
    'admin_audio_room_custom_price_hint' => 'Devre dışıyken içerik üreticileri onaylı bir fiyat seçmek zorundadır.',
    'admin_audio_room_pricing' => 'Fiyatlandırma kuralları',
    'admin_audio_room_pricing_hint' => 'Tutarlar site para birimini ve genel ödeme komisyonu ile vergi ayarlarını kullanır.',
    'admin_audio_room_price_presets' => 'Hazır fiyatlar',
    'admin_audio_room_price_presets_hint' => 'Virgülle ayrılmış pozitif tutarlar.',
    'admin_audio_room_min_price' => 'En düşük ücretli giriş',
    'admin_audio_room_max_price' => 'En yüksek ücretli giriş',
    'admin_audio_room_limits' => 'Süre ve kapasite',
    'admin_audio_room_limits_hint' => 'Günlük kullanım ve katılım sınırlarıyla oda kalitesini koruyun.',
    'admin_audio_room_daily_limit' => 'İçerik üreticisi olmayanlar için günlük dakika',
    'admin_audio_room_zero_unlimited' => '0 sınırsız anlamına gelir.',
    'admin_audio_room_max_speakers' => 'En fazla konuşmacı',
    'admin_audio_room_max_listeners' => 'En fazla dinleyici',
    'admin_audio_room_title_prefix' => 'Varsayılan başlık ön eki',
    'admin_audio_room_title_prefix_placeholder' => 'Örnek: Birlikte sohbet',
    'admin_audio_room_agora_readiness' => 'Agora hazırlığı',
    'admin_audio_room_agora_hint' => 'Sesli Odalar, Canlı Yayın Ayarlarında tanımlanan korumalı Agora bilgilerini kullanır.',
    'admin_audio_room_agora_ready' => 'Hazır',
    'admin_audio_room_agora_missing' => 'Yapılandırma gerekli',
    'admin_audio_room_manage_agora' => 'Agora bilgilerini yönet',
    'admin_audio_room_earnings_title' => 'Sesli Oda kazançları',
    'admin_audio_room_earnings_subtitle' => 'Oda biletlerini, bahşişleri, içerik üreticisi net kazançlarını ve platform gelirini inceleyin.',
    'admin_audio_room_earnings_summary' => 'Kazanç özeti',
    'admin_audio_room_earnings_gross' => 'Brüt hacim',
    'admin_audio_room_earnings_creator_net' => 'İçerik üreticisi neti',
    'admin_audio_room_earnings_creator_net_help' => 'Oda içerik üreticilerine aktarılan tutar',
    'admin_audio_room_earnings_platform' => 'Platform geliri',
    'admin_audio_room_earnings_platform_help' => 'Komisyon ve vergi dağılımı',
    'admin_audio_room_earnings_tickets' => 'bilet',
    'admin_audio_room_earnings_tips' => 'bahşiş',
    'admin_audio_room_earnings_successful' => 'başarılı',
    'admin_audio_room_earnings_transactions' => 'İşlemler',
    'admin_audio_room_earnings_manage_rooms' => 'Odaları yönet',
    'admin_audio_room_earnings_settings' => 'Oda ayarları',
    'admin_audio_room_earnings_export' => 'CSV dışa aktar',
    'admin_audio_room_earnings_search' => 'Ara',
    'admin_audio_room_earnings_search_placeholder' => 'Oda, kullanıcı, referans veya kimlik',
    'admin_audio_room_earnings_type' => 'Tür',
    'admin_audio_room_earnings_type_all' => 'Tüm işlem türleri',
    'admin_audio_room_earnings_type_ticket' => 'Oda biletleri',
    'admin_audio_room_earnings_type_tip' => 'Oda bahşişleri',
    'admin_audio_room_earnings_type_ticket_single' => 'Bilet',
    'admin_audio_room_earnings_type_tip_single' => 'Bahşiş',
    'admin_audio_room_earnings_status' => 'Durum',
    'admin_audio_room_earnings_status_all' => 'Tüm durumlar',
    'admin_audio_room_earnings_status_paid' => 'Ödendi',
    'admin_audio_room_earnings_status_completed' => 'Tamamlandı',
    'admin_audio_room_earnings_status_succeeded' => 'Başarılı',
    'admin_audio_room_earnings_status_pending' => 'Bekliyor',
    'admin_audio_room_earnings_status_failed' => 'Başarısız',
    'admin_audio_room_earnings_status_cancelled' => 'İptal edildi',
    'admin_audio_room_earnings_status_canceled' => 'İptal edildi',
    'admin_audio_room_earnings_status_refunded' => 'İade edildi',
    'admin_audio_room_earnings_from' => 'Başlangıç',
    'admin_audio_room_earnings_to' => 'Bitiş',
    'admin_audio_room_earnings_per_page' => 'Sayfa başına',
    'admin_audio_room_earnings_apply' => 'Uygula',
    'admin_audio_room_earnings_clear' => 'Temizle',
    'admin_audio_room_earnings_results' => 'sonuç',
    'admin_audio_room_earnings_empty' => 'Bu filtrelerle eşleşen Sesli Oda işlemi yok.',
    'admin_audio_room_earnings_col_date' => 'Tarih',
    'admin_audio_room_earnings_col_type' => 'Tür',
    'admin_audio_room_earnings_col_reference' => 'Referans',
    'admin_audio_room_earnings_col_room' => 'Oda',
    'admin_audio_room_earnings_col_buyer' => 'Alıcı',
    'admin_audio_room_earnings_col_creator' => 'İçerik üreticisi',
    'admin_audio_room_earnings_col_gross' => 'Brüt',
    'admin_audio_room_earnings_col_net' => 'İçerik üreticisi neti',
    'admin_audio_room_earnings_col_platform' => 'Platform',
    'admin_audio_room_earnings_col_status' => 'Durum',
    'admin_audio_room_earnings_col_invoice' => 'Fatura',
    'admin_audio_room_earnings_view_invoice' => 'Görüntüle',
    'admin_audio_room_earnings_pagination' => 'İşlem sayfaları',
    'admin_audio_room_invoice_label' => 'Fatura',
    'admin_audio_room_invoice_ticket' => 'Sesli Oda bileti',
    'admin_audio_room_invoice_tip' => 'Sesli Oda bahşişi',
    'admin_audio_room_invoice_back' => 'Kazançlara dön',
    'admin_audio_room_invoice_pdf' => 'PDF indir',
    'admin_audio_room_invoice_not_found' => 'Sesli Oda faturası bulunamadı',
    'admin_audio_room_invoice_not_found_help' => 'İşlem tamamlanmamış veya faturası henüz düzenlenmemiş olabilir.',
    'admin_audio_room_invoice_billed_to' => 'Fatura sahibi',
    'admin_audio_room_invoice_creator' => 'İçerik üreticisi',
    'admin_audio_room_invoice_date' => 'Düzenlenme tarihi',
    'admin_audio_room_invoice_reference' => 'Referans',
    'admin_audio_room_invoice_provider' => 'Sağlayıcı',
    'admin_audio_room_invoice_status' => 'Durum',
    'admin_audio_room_invoice_finance' => 'Sesli Oda finansı',
    'admin_audio_room_invoice_gross' => 'Brüt tutar',
    'admin_audio_room_invoice_fee' => 'Platform komisyonu',
    'admin_audio_room_invoice_tax' => 'Vergi dağılımı',
    'admin_audio_room_invoice_net' => 'İçerik üreticisi neti',
    'admin_dashboard_audio_room_gross' => 'Sesli Oda brüt geliri',
    'admin_dashboard_audio_room_creator_net' => 'Sesli Oda içerik üreticisi neti',
    'admin_dashboard_audio_room_platform_fee' => 'Sesli Oda platform geliri',
    'admin_dashboard_audio_room_tickets' => 'Oda bilet geliri',
    'admin_dashboard_audio_room_tips' => 'Oda bahşiş geliri',
    'admin_dashboard_legend_audio_room_tickets' => 'Sesli Oda biletleri',
    'admin_dashboard_legend_audio_room_tips' => 'Sesli Oda bahşişleri',
    'settings_dashboard_audio_room_ticket' => 'Oda bileti',
    'settings_dashboard_audio_room_tip' => 'Oda bahşişi',
    'settings_dashboard_breakdown_audio_room_tickets' => 'Sesli Oda biletleri',
    'settings_dashboard_breakdown_audio_room_tickets_short' => 'Oda biletleri',
    'settings_dashboard_breakdown_audio_room_tips' => 'Sesli Oda bahşişleri',
    'settings_dashboard_breakdown_audio_room_tips_short' => 'Oda bahşişleri',
    'settings_dashboard_empty_audio_room_earnings' => 'Henüz Sesli Oda kazancı kaydedilmedi.',
    'settings_dashboard_recent_audio_room_earnings' => 'Son Sesli Oda kazançları',
    'audio_room_ticket_payment_title' => 'Sesli Oda bileti',
    'audio_room_tip_payment_title' => 'Sesli Oda bahşişi',
    'audio_room_audience_restricted' => 'Bu Sesli Odaya erişemezsiniz.',
    'audio_room_ended' => 'Bu Sesli Oda sona erdi.',
    'audio_room_label' => 'Sesli Oda',
    'audio_room_not_found' => 'Sesli Oda bulunamadı.',
    'audio_room_untitled' => 'Başlıksız Sesli Oda',
    'invalid_audio_room_price' => 'Geçerli bir Sesli Oda fiyatı girin.',
    'settings_payments_type_audio_room_ticket' => 'Sesli Oda bileti',
    'settings_payments_type_audio_room_tip' => 'Sesli Oda bahşişi',
    'invoice_line_audio_room_ticket_description' => 'Sesli Oda bileti: %s',
    'invoice_line_audio_room_tip_description' => 'Sesli Oda bahşişi: %s',
]);

$localized = static function (array $overrides) use ($eng): array {
    return array_replace($eng, $overrides);
};

return [
    'eng' => $eng,
    'tr' => $tr,
    'de' => $localized([
        'admin_menu_audio_rooms' => 'Audio-Räume', 'admin_menu_audio_room_earnings' => 'Audio-Raum-Einnahmen', 'admin_menu_settings_audio_rooms' => 'Audio-Raum-Einstellungen',
        'admin_audio_rooms_title' => 'Audio-Räume', 'admin_audio_rooms_intro' => 'Live-Räume, Teilnahme, Zugriff und Einnahmen verwalten.', 'admin_audio_rooms_manage' => 'Räume verwalten',
        'admin_audio_room_settings_title' => 'Audio-Raum-Einstellungen', 'admin_audio_room_settings_intro' => 'Verfügbarkeit, bezahlten Zugriff und Kapazität zentral verwalten.',
        'admin_audio_room_features' => 'Funktionen und Zugriff', 'admin_audio_room_pricing' => 'Preisregeln', 'admin_audio_room_limits' => 'Dauer und Kapazität',
        'admin_audio_room_earnings_title' => 'Audio-Raum-Einnahmen', 'admin_audio_room_earnings_transactions' => 'Transaktionen', 'admin_audio_room_earnings_export' => 'CSV exportieren',
        'admin_audio_room_earnings_search' => 'Suchen', 'admin_audio_room_earnings_apply' => 'Anwenden', 'admin_audio_room_earnings_clear' => 'Zurücksetzen',
        'admin_audio_room_earnings_status_all' => 'Alle Status', 'admin_audio_room_earnings_status_paid' => 'Bezahlt', 'admin_audio_room_earnings_status_pending' => 'Ausstehend',
        'admin_audio_room_invoice_label' => 'Rechnung', 'admin_audio_room_invoice_pdf' => 'PDF herunterladen', 'admin_audio_room_invoice_back' => 'Zurück zu Einnahmen',
        'settings_dashboard_recent_audio_room_earnings' => 'Neueste Audio-Raum-Einnahmen', 'audio_room_ticket_payment_title' => 'Audio-Raum-Ticket', 'audio_room_tip_payment_title' => 'Audio-Raum-Trinkgeld',
    ]),
    'es' => $localized([
        'admin_menu_audio_rooms' => 'Salas de audio', 'admin_menu_audio_room_earnings' => 'Ingresos de salas de audio', 'admin_menu_settings_audio_rooms' => 'Ajustes de salas de audio',
        'admin_audio_rooms_title' => 'Salas de audio', 'admin_audio_rooms_intro' => 'Administra salas en vivo, asistencia, acceso e ingresos.', 'admin_audio_rooms_manage' => 'Administrar salas',
        'admin_audio_room_settings_title' => 'Ajustes de salas de audio', 'admin_audio_room_features' => 'Funciones y acceso', 'admin_audio_room_pricing' => 'Reglas de precios', 'admin_audio_room_limits' => 'Duración y capacidad',
        'admin_audio_room_earnings_title' => 'Ingresos de salas de audio', 'admin_audio_room_earnings_transactions' => 'Transacciones', 'admin_audio_room_earnings_export' => 'Exportar CSV',
        'admin_audio_room_earnings_search' => 'Buscar', 'admin_audio_room_earnings_apply' => 'Aplicar', 'admin_audio_room_earnings_clear' => 'Limpiar',
        'admin_audio_room_earnings_status_all' => 'Todos los estados', 'admin_audio_room_earnings_status_paid' => 'Pagado', 'admin_audio_room_earnings_status_pending' => 'Pendiente',
        'admin_audio_room_invoice_label' => 'Factura', 'admin_audio_room_invoice_pdf' => 'Descargar PDF', 'admin_audio_room_invoice_back' => 'Volver a ingresos',
        'settings_dashboard_recent_audio_room_earnings' => 'Ingresos recientes de salas de audio', 'audio_room_ticket_payment_title' => 'Entrada de sala de audio', 'audio_room_tip_payment_title' => 'Propina de sala de audio',
    ]),
    'fr' => $localized([
        'admin_menu_audio_rooms' => 'Salons audio', 'admin_menu_audio_room_earnings' => 'Revenus des salons audio', 'admin_menu_settings_audio_rooms' => 'Réglages des salons audio',
        'admin_audio_rooms_title' => 'Salons audio', 'admin_audio_rooms_intro' => 'Gérez les salons en direct, la participation, l’accès et les revenus.', 'admin_audio_rooms_manage' => 'Gérer les salons',
        'admin_audio_room_settings_title' => 'Réglages des salons audio', 'admin_audio_room_features' => 'Fonctions et accès', 'admin_audio_room_pricing' => 'Règles de tarification', 'admin_audio_room_limits' => 'Durée et capacité',
        'admin_audio_room_earnings_title' => 'Revenus des salons audio', 'admin_audio_room_earnings_transactions' => 'Transactions', 'admin_audio_room_earnings_export' => 'Exporter en CSV',
        'admin_audio_room_earnings_search' => 'Rechercher', 'admin_audio_room_earnings_apply' => 'Appliquer', 'admin_audio_room_earnings_clear' => 'Effacer',
        'admin_audio_room_earnings_status_all' => 'Tous les statuts', 'admin_audio_room_earnings_status_paid' => 'Payé', 'admin_audio_room_earnings_status_pending' => 'En attente',
        'admin_audio_room_invoice_label' => 'Facture', 'admin_audio_room_invoice_pdf' => 'Télécharger le PDF', 'admin_audio_room_invoice_back' => 'Retour aux revenus',
        'settings_dashboard_recent_audio_room_earnings' => 'Revenus récents des salons audio', 'audio_room_ticket_payment_title' => 'Billet de salon audio', 'audio_room_tip_payment_title' => 'Pourboire de salon audio',
    ]),
    'pt' => $localized([
        'admin_menu_audio_rooms' => 'Salas de áudio', 'admin_menu_audio_room_earnings' => 'Ganhos das salas de áudio', 'admin_menu_settings_audio_rooms' => 'Configurações das salas de áudio',
        'admin_audio_rooms_title' => 'Salas de áudio', 'admin_audio_rooms_intro' => 'Gerencie salas ao vivo, participação, acesso e ganhos.', 'admin_audio_rooms_manage' => 'Gerenciar salas',
        'admin_audio_room_settings_title' => 'Configurações das salas de áudio', 'admin_audio_room_features' => 'Recursos e acesso', 'admin_audio_room_pricing' => 'Regras de preço', 'admin_audio_room_limits' => 'Duração e capacidade',
        'admin_audio_room_earnings_title' => 'Ganhos das salas de áudio', 'admin_audio_room_earnings_transactions' => 'Transações', 'admin_audio_room_earnings_export' => 'Exportar CSV',
        'admin_audio_room_earnings_search' => 'Pesquisar', 'admin_audio_room_earnings_apply' => 'Aplicar', 'admin_audio_room_earnings_clear' => 'Limpar',
        'admin_audio_room_invoice_label' => 'Fatura', 'admin_audio_room_invoice_pdf' => 'Baixar PDF', 'admin_audio_room_invoice_back' => 'Voltar aos ganhos',
        'settings_dashboard_recent_audio_room_earnings' => 'Ganhos recentes das salas de áudio', 'audio_room_ticket_payment_title' => 'Ingresso da sala de áudio', 'audio_room_tip_payment_title' => 'Gorjeta da sala de áudio',
    ]),
    'sk' => $localized([
        'admin_menu_audio_rooms' => 'Audio miestnosti', 'admin_menu_audio_room_earnings' => 'Príjmy z audio miestností', 'admin_menu_settings_audio_rooms' => 'Nastavenia audio miestností',
        'admin_audio_rooms_title' => 'Audio miestnosti', 'admin_audio_rooms_manage' => 'Spravovať miestnosti', 'admin_audio_room_settings_title' => 'Nastavenia audio miestností',
        'admin_audio_room_features' => 'Funkcie a prístup', 'admin_audio_room_pricing' => 'Pravidlá cien', 'admin_audio_room_limits' => 'Trvanie a kapacita',
        'admin_audio_room_earnings_title' => 'Príjmy z audio miestností', 'admin_audio_room_earnings_transactions' => 'Transakcie', 'admin_audio_room_earnings_export' => 'Exportovať CSV',
        'admin_audio_room_earnings_search' => 'Hľadať', 'admin_audio_room_earnings_apply' => 'Použiť', 'admin_audio_room_earnings_clear' => 'Vymazať',
        'admin_audio_room_invoice_label' => 'Faktúra', 'admin_audio_room_invoice_pdf' => 'Stiahnuť PDF', 'admin_audio_room_invoice_back' => 'Späť na príjmy',
        'audio_room_ticket_payment_title' => 'Vstupenka do audio miestnosti', 'audio_room_tip_payment_title' => 'Prepitné v audio miestnosti',
    ]),
    'ar' => $localized([
        'admin_menu_audio_rooms' => 'الغرف الصوتية', 'admin_menu_audio_room_earnings' => 'أرباح الغرف الصوتية', 'admin_menu_settings_audio_rooms' => 'إعدادات الغرف الصوتية',
        'admin_audio_rooms_title' => 'الغرف الصوتية', 'admin_audio_rooms_intro' => 'إدارة الغرف المباشرة والحضور والوصول والأرباح.', 'admin_audio_rooms_manage' => 'إدارة الغرف',
        'admin_audio_room_settings_title' => 'إعدادات الغرف الصوتية', 'admin_audio_room_features' => 'الميزات والوصول', 'admin_audio_room_pricing' => 'قواعد التسعير', 'admin_audio_room_limits' => 'المدة والسعة',
        'admin_audio_room_earnings_title' => 'أرباح الغرف الصوتية', 'admin_audio_room_earnings_transactions' => 'المعاملات', 'admin_audio_room_earnings_export' => 'تصدير CSV',
        'admin_audio_room_earnings_search' => 'بحث', 'admin_audio_room_earnings_apply' => 'تطبيق', 'admin_audio_room_earnings_clear' => 'مسح',
        'admin_audio_room_earnings_status_all' => 'كل الحالات', 'admin_audio_room_earnings_status_paid' => 'مدفوع', 'admin_audio_room_earnings_status_pending' => 'قيد الانتظار',
        'admin_audio_room_invoice_label' => 'فاتورة', 'admin_audio_room_invoice_pdf' => 'تنزيل PDF', 'admin_audio_room_invoice_back' => 'العودة إلى الأرباح',
        'settings_dashboard_recent_audio_room_earnings' => 'أحدث أرباح الغرف الصوتية', 'audio_room_ticket_payment_title' => 'تذكرة غرفة صوتية', 'audio_room_tip_payment_title' => 'إكرامية غرفة صوتية',
    ]),
];
